version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql    
  web:
    depends_on:
      - db
    build:
      context: mangastyleapp
    volumes:
      - ./mangastyleapp:/app
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    
volumes:
  db_data: