version: '3.9'
services:
  db:
    container_name: mysqldb
    image: mysql:8.0
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mangastyle
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - db_data:/var/lib/mysql    
    networks:
      - backend
  web:
    container_name: djangoapp
    build:
      context: mangastyleapp
    volumes:
      - ./mangastyleapp:/app
    networks:
      - backend
    ports:
      - '8000:8000'
    environment:
      - DEBUG=True
      - DJANGO_SECRET=test_secret_123
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DB_ENGINE=django.db.backends.mysql
      - DB_HOST=db
      - DB_PORT=3306
      - MYSQL_DATABASE=mangastyle
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_CHARSET=utf8mb4
    depends_on:
      - db
    command: python manage.py runserver
    
volumes:
  db_data:

networks:
  backend:
    driver: bridge