version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file:
      - .env.prod.db
    volumes:
      - db_data:/var/lib/mysql    
  web:
    depends_on:
      - db
    build:
      context: ./mangastyleapp
      dockerfile: Dockerfile.prod
    volumes:
      - static_volume:/app/staticfiles
    env_file:
      - ./.env.prod
    command: gunicorn mangastyleapp.wsgi:application --bind 0.0.0.0:8000
  nginx:
    build:
      context: ./nginx
    volumes:
      - static_volume:/app/staticfiles
    ports:
      - '80:80'
    depends_on:
      - web

volumes:
  db_data:
  static_volume: