version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file:
      - .env.dev.db
    volumes:
      - db_data:/var/lib/mysql    
    networks:
      - backend
  web:
    depends_on:
      - db
    container_name: djangoapp
    build:
      context: mangastyleapp
    volumes:
      - ./mangastyleapp:/app
    networks:
      - backend
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    command: python manage.py runserver 0.0.0.0:8000
    
volumes:
  db_data:

networks:
  backend:
    driver: bridge