version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    env_file:
      - .env.dev
    volumes:
      - db_data:/var/lib/mysql    
    networks:
      - backend
  web:
    depends_on:
      - db
    build:
      context: .
    volumes:
      - .:/app # mount our code to /app on the container
    networks:
      - backend
    ports:
      - '8000:8000'
    env_file:
      - .env.dev
    
volumes:
  db_data:

networks:
  backend:
    driver: bridge