version: '3.9'
services:
  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql    
  web:
    depends_on:
      - db
    build:
      context: mangastyleapp
    ports:
      - 8000:8000
    env_file:
      - ./.env.prod
    command: gunicorn mangastyleapp.wsgi:application --bind 0.0.0.0:8000

volumes:
  db_data: