# Generated by Django 4.1 on 2022-08-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_twitterartist_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaattachment',
            name='media_style',
            field=models.CharField(default='', max_length=10),
        ),
    ]
