# Generated by Django 4.1 on 2022-08-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_twitterartist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterartist',
            name='name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
