# Generated by Django 4.1.1 on 2023-11-23 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0017_twitterartist_hide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaattachment',
            name='style',
        ),
        migrations.RemoveField(
            model_name='mediaattachment',
            name='training_data',
        ),
    ]
