# Generated by Django 4.1 on 2022-08-16 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_id', models.CharField(max_length=40, unique=True)),
                ('media_url', models.URLField(unique=True)),
                ('media_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MediaTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.CharField(max_length=40, unique=True)),
                ('tweet_url', models.URLField(unique=True)),
                ('likes_count', models.IntegerField(default=0)),
                ('retweets_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField()),
                ('lang', models.CharField(blank=True, default='', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='TwitterArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=15, unique=True)),
                ('followers_count', models.IntegerField(default=0)),
                ('profile_image_url', models.URLField(blank=True, default='')),
            ],
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
        migrations.AddField(
            model_name='mediatweet',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trending_tweets_app.twitterartist'),
        ),
        migrations.AddField(
            model_name='mediaattachment',
            name='parent_tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trending_tweets_app.mediatweet'),
        ),
    ]
