# Generated by Django 4.1 on 2022-08-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0005_mediaattachment_media_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterartist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
