# Generated by Django 4.1 on 2022-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0006_alter_twitterartist_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitterartist',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
