# Generated by Django 4.1 on 2022-08-22 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0008_alter_twitterartist_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediatweet',
            name='tweet_url',
        ),
        migrations.AddField(
            model_name='mediatweet',
            name='text',
            field=models.URLField(blank=True, default='', max_length=560),
        ),
    ]
