# Generated by Django 4.1 on 2022-08-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0009_remove_mediatweet_tweet_url_mediatweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediatweet',
            name='possibly_sensitive',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
