# Generated by Django 4.1 on 2022-08-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0010_mediatweet_possibly_sensitive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatweet',
            name='author',
            field=models.CharField(max_length=40, blank=False),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='parent_tweet',
            field=models.CharField(max_length=40, blank=False),
        ),
    ]
