# Generated by Django 4.1 on 2022-08-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0012_alter_mediaattachment_parent_tweet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterartist',
            name='last_updated',
            field=models.DateTimeField(),
        ),
    ]
