# Generated by Django 4.1 on 2022-09-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0013_alter_twitterartist_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaattachment',
            name='training_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mediaattachment',
            name='media_style',
            field=models.SmallIntegerField(blank=True, default=-1),
        ),
    ]
