# Generated by Django 4.1 on 2022-09-03 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0014_mediaattachment_training_data_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mediaattachment',
            old_name='media_style',
            new_name='style',
        ),
    ]
