# Generated by Django 4.1 on 2022-09-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trending_tweets_app', '0015_rename_media_style_mediaattachment_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediatweet',
            name='text',
            field=models.CharField(blank=True, default='', max_length=560),
        ),
    ]
